### PR TITLE
Tic-Tac-Toe Game Project - Milestone 2: User Interface

### PR DESCRIPTION
**Pull request by Leandro-Barretoo**
In this pull request, we worked on the planning of the Tic-Tac-Toe game.
In order to display the flow of the game we used mainly:
- puts - to display information
- gets - to get player data

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Leandro-Barretoo and @ourandco  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
### Basic game flow
- [ ] game asks the player to select from available moves
- [ ] game informs player if the selected move is invalid (without computing what an invalid move is)
- [ ] game displays board after the player move (without computing which spots on the board are taken)
- [ ] game informs player if the selected move is a winning move (without computing the winning move)
- [ ] game informs player if the selected move is a draw move (without computing draw)
- [ ] game repeats all actions for the next player's move

### Implementation details
- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [ ] Inside the loop, you should call actions repeated for each move
- [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by mimipeshy** [comment]
## STATUS :CHANGES REQUIRED :red_circle: :recycle: 

#### Hey team @Leandro-Barretoo and @ourandco :wave: a good job for the work you have done so far.
 However, you still have not implemented the changes as requested by the previous TSE. Kindly work on all the feedback given. It is important to work on any feedback given by a TSE  before requesting another review. 

That's all :smile: ,  submit another review when done.
If you need any help or have any questions, drop me a message on slack, and will be glad to help

Regards
Peris Ndanu

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED**

## **Hello @Leandro-Barretoo and @ourandco handshake**

Great work on the project so far +1, all your efforts are visible from the changes made but we have to make a few more changes to get this milestone Approved. Let me break down the changes for you.

## **Required Changes:**

1. The game doesn't display who the next player is. This should change every other turn/round of play.
2. All user inputs should be digits between 1-9, your game accepts any input including invalid inputs.
3. All user inputs made each and every round is replacing the previous player's move, and they all are placed in position index '0'.
4. The game doesn't inform players if the selected move is a winning or a draw move. Create a conditional check for either of the two.

Please ensure that you make the required changes in this milestone so that you carry on to the next one.

 Reach out to me on slack @roymukuye in case you have any inquiries.

Cheers!

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **Status: Changes Required** 

### Hello team!!

Again, I applaud you all for your efforts towards this project. Let's make these few changes before we can approve this milestone.

## Required Changes:

- [ ]  An invalid move from the player ends the game. This should prompt the current player to enter a valid move, and not terminate the game.

- [ ]  Again, the user inputs are still being placed in position index '0'. Meaning that it replaces the previous move made.

Keep up with the efforts towards this project, you are almost there.
Cheers!!

**Comment by Leandro-Barretoo** [comment]
🙏  Please have some mercy

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Status: Changes Required 
Hello Team,
You have done a good job so far but, there are a few minor changes that need to be made before moving ahead. Let's have a look at them.
Required Changes:
- [ ]  [REQUIRED] The user inputs are always placed in position index '2' or '2' and '5'. Meaning that it replaces the previous move made.

Tips: 
1) Use an Array.
2) After each move:
- Put symbols inside the array based on the user input.
- Then Display the board with the content of this array.
Happy coding !!!
Rindra Josia

**Comment by Leandro-Barretoo** [comment]
I wish your mother lives 1000 years
-Alamgir

**Review by NtwaliHeritier — APPROVED** [review]
Status: Approved
Hello team
You are good to merge this branch and work on another milestone.

Best of luck

**Pull request merged**
